platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: gppkgs

params:
  DD_SOURCE_HOST:
  DD_DEST_HOST:
  DD_USER:
  DD_PW:
  DD_ENCRYPTED_PW:
  OS: RHEL

run:
  path: gpbackup/ci/scripts/ddboost-plugin-tests.bash
