platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: gppkgs

params:
  DD_SOURCE_HOST:
  DD_DEST_HOST:
  DD_USER:
  DD_PW:
  DD_ENCRYPTED_PW:
  OS: RHEL
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BUCKET:
  REGION:

run:
  path: gpbackup/ci/scripts/ddboost-plugin-perf.bash
