platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: gpdb_src
- name: sqldump

outputs:
- name: artifacts

run:
  path: gpbackup/ci/scripts/gpbackup-regression.bash
